In [1]:
import torch

In [3]:
sample = torch.tensor([10,11])
sample.shape

torch.Size([2])

In [4]:
x = torch.tensor([[10,11],[1,2]])
x.shape

torch.Size([2, 2])

In [5]:
y = torch.tensor([[10],[11]])
y.shape

torch.Size([2, 1])

In [6]:
import torch
import plotly.graph_objs as go
import plotly.offline as pyo

# Create a 3-dimensional tensor
a = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Create a list of all the x, y, and z values in the tensor
x_vals = []
y_vals = []
z_vals = []
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            x_vals.append(i)
            y_vals.append(j)
            z_vals.append(k)

# Create a Plotly 3D scatter plot
trace = go.Scatter3d(
    x=x_vals,
    y=y_vals,
    z=z_vals,
    mode='markers',
    marker=dict(
        size=5,
        color=a.flatten(),
        colorscale='Viridis',
        opacity=0.8
    )
)

# Create the plot layout
layout = go.Layout(
    margin=dict(l=0, r=0, b=0, t=0),
    scene=dict(
        xaxis=dict(title='Dimension 1'),
        yaxis=dict(title='Dimension 2'),
        zaxis=dict(title='Dimension 3')
    )
)

# Combine the trace and layout into a figure and display it
fig = go.Figure(data=[trace], layout=layout)
pyo.plot(fig, filename='tensor.html')


'tensor.html'

# Tensor with Random Numbers

torch.zeros((shape tuple))

In [ ]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[6, 6, 7, 3],
        [8, 6, 4, 1],
        [9, 9, 6, 6]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4,2))

tensor([[[0, 7],
         [7, 5],
         [3, 1],
         [8, 0]],

        [[2, 2],
         [1, 3],
         [9, 7],
         [1, 1]],

        [[4, 3],
         [9, 8],
         [6, 2],
         [8, 8]]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4,4))

tensor([[[6, 7, 2, 4],
         [6, 8, 8, 2],
         [1, 2, 4, 1],
         [8, 8, 4, 4]],

        [[4, 2, 4, 8],
         [6, 3, 5, 3],
         [8, 4, 9, 9],
         [4, 2, 3, 2]],

        [[8, 0, 6, 6],
         [2, 7, 1, 6],
         [2, 9, 5, 6],
         [4, 1, 8, 8]]])